# Generated by Django 3.2.3 on 2021-06-21 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0003_auto_20210621_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
